### ISSUE TITLE
BASIC OPEN returning ST=0 when trying to OPEN a file that doesn't exist when using R45 on hardware

### ISSUE THREAD

**Issue by voidstar78** [X16Community/x16-rom#205]
10 X$="TEST.DAT,S,R"
  20 OPEN 2,8,2,X$:FE%=(ST=0)
  25 PRINT ST
  30 CLOSE 2
  40 PRINT FE%
  (RUN the above in a folder or SD-card where file specified in X$ does NOT exist)

Did the above program.  SD card inserted on hardware.    I've tried R45, R44, and R43 - got same result on hardware:  ST remains value 0, so it thinks the file exist even if it is not located on the disk drive anywhere.      My SMC is 45.1.0   VERA 0.3.1

On the R45 emulator, the above code is showing ST=66 after trying to OPEN on a filename that doesn't exist - which I think is correct behavior.   So, suspect the SMC is behaving differently between emu and H/W in terms of reporting when a file has been opened or not (resulting in BASIC to set the incorrect ST value).

**Comment by mooinglemur** [comment]
Just to be clear, I believe this is a distinction between DOS/SD card behavior and HostFS, *NOT* hardware vs. emulator.  

If we're going by CBM behavior, what's happening on DOS/SD card is consistent with that behvior

![image](https://github.com/X16Community/x16-rom/assets/395186/6d993492-2bcb-4799-b17b-bee691899735)

In this case, it's HostFS which is deviating from expected behavior.

OPEN should return success as long as the drive responded.  The fact that HostFS is setting the status is actually wrong.

In order to check for the error, just like on C64, you need to open channel 15 and read the status.

![image](https://github.com/X16Community/x16-rom/assets/395186/d014db1c-e69c-4fdc-97bc-1a62efd231da)

![image](https://github.com/X16Community/x16-rom/assets/395186/059e17de-a174-4a2b-9d77-bfc0b5b568b1)

**Comment by mooinglemur** [comment]
Emulator behavior fixed in https://github.com/X16Community/x16-emulator/pull/179
