### ISSUE TITLE
Ability to adjust the hot spot of the mouse cursor

### ISSUE THREAD

**Issue by DragWx** [X16Community/x16-rom#258]
As far as I can tell, the mouse cursor's hot spot is always the top-left corner of the sprite. Common non-top-left-corner cursors include resize arrows, grab-hands, the text-beam cursor, and *sometimes* pointer finger cursors.

This can be worked around in software (with caveats), but I think the Kernal supporting this is more ideal.

**Comment by mooinglemur** [comment]
Committing a change that allows for this functionality.  Documentation will be added soon to `x16-docs`

Put the 16-bit sprite offset into `r0` (X coordinate) and `r1` (Y coordinate), clear carry (to set value), and load A with #3 (the extapi call number). then `jsr extapi`

Since the hotspot of the cursor will be positive, the sprite offset will need to be negative

```x86asm
; configure your mouse sprite here

; configure mouse before setting offset
lda #$ff
ldy #0
ldx #0
jsr $ff68 ; mouse_config

lda #<(-16)
sta r0L
sta r1L
lda #>(-16)
sta r0H
sta r1H
lda #3
clc
jsr $feab ; extapi
```
