### ISSUE TITLE
Make doesn't build if certain files are changed

### ISSUE THREAD

**Issue by Yazwh0** [X16Community/x16-rom#50]
There are plenty of source files that changes are ignored by `make`. Like the basic .s files.

**Comment by mooinglemur** [comment]
This is such a short build that `make clean all` finishes in about 3 seconds for me, so that's what I've become accustomed to using.  There are other weird behaviors that can happen also, such as defining the version number on one build and omitting it on the next.

It would be good to make this better for sure, especially for all of the .s files, but there comes a point where the Makefile could get unwieldy if we wanted to keep the dependencies consistent, particularly for how the include files are used across banks.

BASIC doesn't use exports for its own build, but rather it's structured as one big .include chain, which does mean the Makefile would have to be informed about that dependency chain.

**Comment by Yazwh0** [comment]
Then `make clean all` should be the default. Otherwise debugging the ROM can be difficult as you assume you've changed something, yet it hasn't been compiled.

**Comment by Yazwh0** [comment]
For me a `make clean all` takes 21s. On a Ryzan 9 7900X. Is WSL such an overhead?

`time make clean all` result:
![image](https://user-images.githubusercontent.com/90315107/224511470-07767bfa-62df-4c89-99bf-5e894daa7685.png)

**Comment by mooinglemur** [comment]
When compiling cc65 on Windows using MSYS2 using the GitHub runners, it takes about 8 times as long as on Linux.  There's some serious overhead somewhere when it comes to file I/O.

**Comment by gillham** [comment]
With the change below my 'time make' always does a clean build and averages about 1.5 seconds.

diff --git a/Makefile b/Makefile
index cc548db..cc54a29 100644
--- a/Makefile
+++ b/Makefile
@@ -264,7 +264,7 @@ ROM_LABELS=$(BUILD_DIR)/rom_labels.h
 ROM_LST=$(BUILD_DIR)/rom_lst.h
 GIT_SIGNATURE=$(BUILD_DIR)/../signature.bin
 
-all: $(BUILD_DIR)/rom.bin $(ROM_LABELS) $(ROM_LST)
+all: clean $(BUILD_DIR)/rom.bin $(ROM_LABELS) $(ROM_LST)
 
 $(BUILD_DIR)/rom.bin: $(BANK_BINS)
        cat $(BANK_BINS) > $@
