### ISSUE TITLE
add a HELP command

### ISSUE THREAD

**Issue by irmen** [X16Community/x16-rom#64]
For new users the first thing they'll likely be typing is HELP.

There is no help command right now. I think there should be one giving a concise friendly message.

- what short help message should we use.
- pointing to a guide? what/where?
- pointing to the docs?

note that an URL or perhaps even a file on disk, can change or disappear

**Comment by tomxp411** [comment]
This has been asked enough times that it's worth discussing. 

Thoughts:
We could build something similar to the Unix `man` command. When the user types HELP with no arguments, it would load the table of contents from a file on disk. The user could move through the TOC to read specific chapters by typing HELP with an argument, like HELP PRINT. 

The TOC and help file would be built during the doc build process, by parsing the .md file(s) and creating the TOC and index. This would give the HELP program something to work with. 

This could easily be used as a general purpose doc reader and help system for third party applications, too by typing HELP with a filename, where the filename is the index of the user-created document. 

As a fallback, when no help file is present, then print something like "Visit us online at Commanderx16.com to download instructions."

**Comment by tomxp411** [comment]
I has also been suggested that the HELP command just loads and runs HELP.PRG. The problem with this is it would blow away the currently loaded BASIC program. I don't see that as a viable option.

**Comment by Frosty-J** [comment]
Related to https://github.com/commanderx16/x16-rom/issues/157  :)

**Comment by mobluse** [comment]
Since X16 BASIC v2 is based on a Microsoft BASIC the formats for MSX BASIC v2 could be used: https://github.com/Konamiman/MSX2-Technical-Handbook/blob/master/md/Chapter2.md/
I've written an X16 program  that lists all commands and functions using the ROM: https://cx16forum.com/forum/viewtopic.php?p=26689#p26689 . All that is needed is to write a program that extracts the formats and descriptions from the above file and add similar information for the X16 keywords that are not in MSX2 BASIC, and you also need to correct syntax from MSX2 that doesn't work in X16.
